name: Docker Image CI

on:
  push:
    branches: [ "main", "ghcr" ]
  workflow_dispatch:

env:
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Rootfs
      run: |
        sudo apt install -y debootstrap podman
        cd rootfs
        sudo sh build.sh
        cd ..

    - name: Vib
      run: |
        wget https://github.com/Vanilla-OS/Vib/releases/download/v0.2.7/vib
        chmod +x vib
        ./vib build recipe.yml
        sed -i '/\/var\/tmp\/*/{d}' Containerfile

    - name: Build the Docker image
      run: podman image build -f Containerfile --tag vanillaos/pico:${{ github.ref_name }} .

    # - name: Push To Registry
    #   uses: redhat-actions/push-to-registry@v2.7
    #   with:
    #     image: vanillaos/pico
    #     tags: ${{ github.ref_name }}
    #     registry: ${{ secrets.NEXUS_REGISTRY }}
    #     username: ${{ secrets.NEXUS_USER }}
    #     password: ${{ secrets.NEXUS_PSW }}
    #     tls-verify: false

    # Push the image to GHCR (Image Registry)
    - name: Push To GHCR
      uses: redhat-actions/push-to-registry@v2
      id: push
      with:
        image: ${{ steps.build-action.outputs.image }}
        tags: ${{ github.ref_name }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        extra-args: |
          --disable-content-trust

    - uses: actions/upload-artifact@v3
      with:
        name: vanilla-pico-rootfs
        path: rootfs/vanilla-pico.tar.zst
