name: Vib release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:

  generate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache APT packages
      uses: actions/cache@v4
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt
        restore-keys: |
          ${{ runner.os }}-apt

    - name: Rootfs
      run: |
        sudo apt install -y debootstrap podman
        cd rootfs
        sudo sh build.sh
        cd ..

    - uses: vanilla-os/vib-gh-action@v0.3.2-2

    - name: Save Containerfile
      id: save-containerfile
      run: echo "::set-output name=file_path::Containerfile"

  commit:

    runs-on: ubuntu-latest
    needs: generate

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: 'release'

      - name: Commit Containerfile
        run: |
          file_path="${{ steps.save-containerfile.outputs.file_path }}"
          cp $file_path Containerfile
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Containerfile
          git commit -m "release: ${GITHUB_REF#refs/tags/}"
          git push
